### ISSUE TITLE
[RCC3, RCC8] Can they have a quantisation factor like RCC2?

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#106]
@pet1330 Can RCC3, RCC8 have a quantisation factor like RCC2 like in #100 ? Can't think of an easy way to do so if even possible?

**Comment by pet1330** [comment]
from a technical point of view it wouldn't be too hard to impliment, but I don't know if they should have it as they have states such as EC which would never be used if quantisation factors were introduced. But assign this issue to me and I'll have a think about it.

**Comment by cdondrup** [comment]
Can't assign you because you have to be in a team that is listed under collaborators of this repository. I cannot create teams any more as my owner status was revoked at some point before the last review. Maybe @marc-hanheide or @hawesie can create a `strands_qsr_lib_collaborators` team to include you since you are involved in the development quite a lot. The you could be assigned.

**Comment by yianni** [comment]
@marc-hanheide @hawesie ^^ :+1:

**Comment by yianni** [comment]
> from a technical point of view it wouldn't be too hard to impliment, but I don't know if they should have it as they have states such as EC which would never be used if quantisation factors were introduced. But assign this issue to me and I'll have a think about it.

Yes it is because of these "additional/intermediate" states between dc and c that I can't think of a way to get a q-factor for these two QSRs.

**Comment by marc-hanheide** [comment]
@pet1330 is now a contributor via @strands-project/strands_qsr_lib-contributors

**Comment by pet1330** [comment]
This issue was resolved in #128
