### ISSUE TITLE
Have a dev branch.

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#110]
@marc-hanheide @hawesie 

I think we need a dev branch here also as it can occur (like at this time) that PRs hold development or will make it too complicated to deal with conflicts and duplicating work.

What are the complications for having an extra dev branch, most notably with respect to jenkins?

**Comment by yianni** [comment]
Quoting @cdondrup in #109 . Closing the ticket and abandoning the idea of a dev branch.

**Comment by marc-hanheide** [comment]
Not quite sure I fully understand the issue here. You could perfectly have a second devel branch. But Jenkins only supports one release and one devel branch. PR support and push-triggered builds only work on the devel branch. Releases work on the release branch. Usually, we have both being the same so we test continuously before releasing. We should stick to that IMO. You could configure another entry in rosdistro e.g. called strands_qsr_lib_beta, with another devel branch but it would complicate things. I don't think it really is needed...

**Comment by yianni** [comment]
Thanks @marc-hanheide for the reply. Well, there is no dev branch for this repo; but I do agree with @cdondrup that it will be a nightmare to maintain and keep in sync both. So let's leave it to only release master branch. If things really get problematic (which I doubt as it is kind of a the first time that development has to wait for a bit for a PR to get merged first) then we can reconsider if the benefits outweigh the nightmare to come.
