### ISSUE TITLE
[QTC] QTC returns numpy arrays?

### ISSUE THREAD

**Issue by PDuckworth** [strands-project/strands_qsr_lib#25]
@cdondrup Does the QTC implementation return np.arrays? 

I think @yianni 's idea was that the multiple qsr implementations would return the same type so we can quickly switch between them. RCC3 implementation returns strings.

**Comment by cdondrup** [comment]
It does return numpy arrys atm, yes. I find strings inherently terrible, especially since I also also use NaN values in the arrays for my QTCbc definition. I see the benefit of strings yes. But why is the message serialised then in the first place?

I can change it to string once I have time which means that I have to create the string first and then recreate the array out of it in my code... :(

**Comment by yianni** [comment]
On 10/03/15 19:54, Christian Dondrup wrote:
>
> It does return numpy arrys atm, yes. I find strings inherently terrible,
>
Why? With strings you can have more descriptive notations, and still you 
can split them out easily by str.split(",") method.
>
> especially since I also also use NaN values in the arrays for my QTCbc 
> definition.
>
You can use NaN values as strings also and then can be easily converted 
into the classic nan type.
>
> I see the benefit of strings yes. But why is the message serialised 
> then in the first place?
>
Not sure I understand this. Maybe we can have a chat what you mean. I 
don't mind changing strings to some other form (lists, arrays) provided 
that there are more flexible, faster, etc. basically there is a good 
reason for that. There are only a couple of QSRs so if a decision as 
such is to be made it better be made at this point.
>
> I can change it to string once I have time which means that I have to 
> create the string first and then recreate the array out of it in my 
> code... :(
>
Let's chat about it at some point but I think that it should be the same 
format whatever that might end to be, otherwise it gets confusing.

Regards,
Yiannis

**Comment by cdondrup** [comment]
OK, let's have a chat next week if that's alright. This week is rather busy for me.

**Comment by yianni** [comment]
Sounds good. Yes, same here, and same for next week but maybe we can find some time for a quick chat.

**Comment by PDuckworth** [comment]
Cool, thanks for the info. Chat next week.
