### ISSUE TITLE
[qsr_prob_rep] Discussion

### ISSUE THREAD

**Issue by yianni** [strands-project/strands_qsr_lib#76]
@cdondrup Excellent initiative and would be useful I think. I have a few questions:
Can you copy and paste the README again or the message from the earlier pull request...
Can you copy and paste the link to your branch, really busy now but I would like to see the code about some things...

The two key points I would like to ask are:
a) standalone use would be really great to be honest.
b) can you ignore the string representation of the QSR and take advantage of the dict one (--future) instead (if havent done so, need to see source)... the thing is that it would be really flexible and powerful as then it allows to compute transitions and emissions on merged QSRs (eg. get RCC8, get QTCB -> merge in to one which currently is supported)

We can chat when we are both free.

Nice one!

**Comment by cdondrup** [comment]
Hi the readme is here: https://github.com/strands-project/strands_qsr_lib/blob/master/qsr_prob_rep/README.md and the code is already merged, so you can just have a look in the repo.

Currently it only uses the string versions of the QSRs but since only QTC is there yet it shouldn't be too hard to change that to use the dict as well. I'll open an issue for that. I have to focus on other things now, but will keep on working on it, but updates won't be as quick I'm afraid...

**Comment by yianni** [comment]
Merge was quick! Was it tested?

Anyway, yes would be great to change from str to dict and I assume since you are the sole user at the moment there is no urgency.

**Comment by cdondrup** [comment]
I wrote unit tests checking the current functionality and since it just added code I took the liberty of merging it.
